DROP TABLE IF EXISTS SCENE;
CREATE TABLE SCENE(
    ID BIGINT NOT NULL,
    RULE_CODE VARCHAR(256) NOT NULL,
    SCENE_NAME VARCHAR(256) NOT NULL,
    EXPRESSION VARCHAR(256) NOT NULL,
    MEMO VARCHAR(256) NOT NULL,
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS RULE;
CREATE TABLE RULE (
    ID BIGINT NOT NULL,
    RULE_CODE VARCHAR(256) NOT NULL,
    RULE_NAME VARCHAR(256) NOT NULL,
    EXPRESSION VARCHAR(256) NOT NULL,
    RULE_TYPE VARCHAR(256) NOT NULL,
    MESSAGE VARCHAR(256) NOT NULL,
    PRIMARY KEY (ID)
);